### ISSUE TITLE
class Resource(metaclass=ResourceBase) - invalid syntax error

### ISSUE THREAD

**Issue by PREM1980** [mpitid/pylabelme#4]
I cloned the repository and when I try to run the command ./labelme.py, I get the following error - 

(test) m@m-ubu1404:~/labelme/pylabelme$ ./labelme.py 
Traceback (most recent call last):
  File "./labelme.py", line 33, in <module>
    import resources
  File "/home/m/.virtualenvs/test/local/lib/python2.7/site-packages/resources/__init__.py", line 1, in <module>
    from .resource import Resource  # noqa
  File "/home/m/.virtualenvs/test/local/lib/python2.7/site-packages/resources/resource.py", line 57
    class Resource(metaclass=ResourceBase):

I have installed resources==0.0.1 

                            ^

**Comment by jabir366** [comment]
I had the same issue. setting the PYTHONPATH environment variable solved my issue

**Comment by lapyrodas** [comment]
hi, how did you configure the environment variable PYTHONPATH @jabir366

**Comment by lucasjinreal** [comment]
Same error here
